version: "3.7"
services:
  runner-strong:
    platform: "linux/amd64"
    build:
      context: ./docker/openmpi
      dockerfile: Dockerfile.dev
    volumes:
      - "./src:/app"
    command: >
      sh -c "chmod +x run-strong.sh && ./run-strong.sh"
  runner-weak:
    platform: "linux/amd64"
    build:
      context: ./docker/openmpi
      dockerfile: Dockerfile.dev
    volumes:
      - "./src:/app"
    command: >
      sh -c "chmod +x run-weak.sh && ./run-weak.sh"
  correctness:
    platform: "linux/amd64"
    build:
      context: ./docker/openmpi
      dockerfile: Dockerfile.dev
    volumes:
      - "./src:/app"
    command: >
      sh -c "chmod +x correctness.sh && ./correctness.sh"      