version: "3.7"
services:
  runner:
    platform: "linux/amd64"
    build:
      context: ./docker/openmpi
      dockerfile: Dockerfile.dev
    volumes:
      - "./src:/app"
    command: >
      sh -c "chmod +x run.sh && ./run.sh"
  correctness:
    platform: "linux/amd64"
    build:
      context: ./docker/openmpi
      dockerfile: Dockerfile.dev
    volumes:
      - "./src:/app"
    command: >
      sh -c "chmod +x correctness.sh && ./correctness.sh"      