version: "3.7"
services:
  openmpi:
    platform: "linux/amd64"
    build:
      context: ./docker/openmpi
      dockerfile: Dockerfile.dev
    volumes:
      - "./src:/app"
    #sh -c "chmod +x run.sh && ./run.sh"
    command: >
      sh -c "cd /app && mpicc main.c -o main.out && mpirun -np 1 --allow-run-as-root ./main.out"